### ISSUE TITLE
Catch.hpp not found

### ISSUE THREAD

**Issue by cibersheep** [czinn/homeworlds#3]
On (Readme)[https://github.com/czinn/homeworlds/blame/master/README.md#L8] is recomended to pull this hpp but it's gone.
It's available here:
https://raw.githubusercontent.com/catchorg/Catch2/master/single_include/catch2/catch.hpp

but I didn't check the origin

**Comment by czinn** [comment]
Added. In hindsight, using a random non-permalink was a bad idea.
